version: 2.1
orbs:
  node: circleci/node@1.1
jobs:
  build:
    docker:
      - image: cimg/node:14.17.5
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
      - run: npm run test