defaults: &defaults
  working_directory: ~/repo

version: 2
jobs:
  build:
    <<: *defaults
      docker:
      - image: cimg/node:14.17.5
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: npm ci
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      # run tests!
      - run: npm run test
      - run: npm run build
      # Persist entire project directory to the next job
      - persist_to_workspace:
          root: dist
          paths:
            - "**"
  deploy:
    <<: *defaults
    docker:
      # specify the version you desire here
      - image: amazon/aws-cli:2.2.31
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Configure AWS CLI
          command: aws configure set default.region ${AWS_DEFAULT_REGION}
      - run:
          name: Configure AWS Access Key ID
          command: aws configure set aws_access_key_id ${AWS_ACCESS_KEY_ID}
      - run:
          name: Configure AWS Secret Access Key
          command: aws configure set aws_secret_access_key ${AWS_SECRET_ACCESS_KEY}
      - run:
          name: Deploy entire directory
          command: aws s3 cp . s3://${BUCKET_NAME} --recursive
 # ...